"""EverWeb report package boundary."""

from everweb.report.evidence_writer import (
    EvidenceConflictError,
    EvidenceCorruptionError,
    EvidenceError,
    EvidenceEventTooLargeError,
    EvidenceReadResult,
    EvidenceRecoveryWarning,
    EvidenceSensitiveContentError,
    EvidenceSerializationError,
    EvidenceWriter,
    EvidenceWriterClosedError,
    read_evidence,
)
from everweb.report.trace_writer import (
    TraceCorruptionError,
    TraceDurability,
    TraceError,
    TraceEventTooLargeError,
    TraceReadResult,
    TraceRecoveryWarning,
    TraceSerializationError,
    TraceWriter,
    TraceWriterClosedError,
    compute_trace_checksum,
    read_trace,
)

__all__ = [
    "EvidenceConflictError",
    "EvidenceCorruptionError",
    "EvidenceError",
    "EvidenceEventTooLargeError",
    "EvidenceReadResult",
    "EvidenceRecoveryWarning",
    "EvidenceSensitiveContentError",
    "EvidenceSerializationError",
    "EvidenceWriter",
    "EvidenceWriterClosedError",
    "TraceCorruptionError",
    "TraceDurability",
    "TraceError",
    "TraceEventTooLargeError",
    "TraceReadResult",
    "TraceRecoveryWarning",
    "TraceSerializationError",
    "TraceWriter",
    "TraceWriterClosedError",
    "compute_trace_checksum",
    "read_evidence",
    "read_trace",
]
